name = "kbsb-hcaptcha-worker"
main = "src/index.js"
compatibility_date = "2022-11-02"
account_id = "26e4da6158b7c941dc9517194d07125c"

[dev]
ip = "100.125.102.16"
port = 8080
local_protocol = "http"

[vars]
# HCAPTCHA_SECRET_KEY # set with secrets
CORS_ORIGIN = '*'

[env.production]
name = "kbsb-hcaptcha-worker"
[env.production.vars]
CORS_ORIGIN = 'https://hcaptcha-cloudflare.kbsb.app' # set to frontend base-URL
